  
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    app: bd
spec:
  type: LoadBalancer 
  ports:
    - port: 3306
  selector:
      app: bd
      tier: mysql
  #externalIPs:
  #  - 80.11.12.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: bd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
  labels:
    app: bd
spec:
  selector:
    matchLabels:
      app: bd
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bd
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "ROOTDEV2021"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim